### ISSUE TITLE
NETLMv2_fmt_plug.c:229: ASAN: heap-buffer-overflow

### ISSUE THREAD

**Issue by loverszhaokai** [magnumripper/JohnTheRipper#1406]
This bug is found by afl.

This problem seems like https://github.com/magnumripper/JohnTheRipper/issues/1405, they are maybe the same problem.

# 1. Reproduce

$  ./configure --enable-asan && make -sj8
$ cat pwfile
```
TL$vYVD8/xSJ/v$uGam4GB8hOjTLQq}BfxJ2/
{smd5}RJaSLb$aKM3H1.h1ycXl5GEVDH1e1
{smd5}eLB0QWeS$Eg.YfWY8clZuCxF0xNr8g.
$1$JVDbG�8K$T9h8HK4LZxeLP:Tilekeychain$Lb:TAxCfpc1
$1$1Cu6fEvv$42ku40
$�$�l5x.xXL$vY��xol2x��������������UBBpERRWcn1
```
$ ./john pwfile
```C
Warning: detected hash type "md5crypt", but the string is also recognized as "aix-smd5"
Use the "--format=aix-smd5" option to force loading these as that type instead
Warning: invalid UTF-8 seen reading out_asan/crashes/id:000020,sig:06,src:000004,op:havoc,rep:16
=================================================================
==26956==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60400000df32 at pc 0x7f02e7b1719b bp 0x7ffeb8694290 sp 0x7ffeb8693a50
WRITE of size 9 at 0x60400000df32 thread T0
    #0 0x7f02e7b1719a in strcat (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x3019a)
    #1 0x553911 in strcat /usr/include/x86_64-linux-gnu/bits/string3.h:142
    #2 0x553911 in prepare /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/NETLMv2_fmt_plug.c:229
    #3 0x74745c in ldr_split_line /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:640
    #4 0x7483e2 in ldr_load_pw_line /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:802
    #5 0x749c96 in read_file /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:135
    #6 0x74c67f in ldr_load_pw_file /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:1000
    #7 0x73fecc in john_load /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/john.c:1006
    #8 0x74162b in john_init /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/john.c:1290
    #9 0x7431d2 in main /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/john.c:1730
    #10 0x7f02e6360ec4 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21ec4)
    #11 0x407032 (/home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/run/john+0x407032)

0x60400000df32 is located 0 bytes to the right of 34-byte region [0x60400000df10,0x60400000df32)
allocated by thread T0 here:
    #0 0x7f02e7b3b7df in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x547df)
    #1 0x75dc54 in mem_alloc_func /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/memory.c:89
    #2 0x5538ef in prepare /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/NETLMv2_fmt_plug.c:224
    #3 0x74745c in ldr_split_line /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:640
    #4 0x7483e2 in ldr_load_pw_line /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:802
    #5 0x749c96 in read_file /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:135
    #6 0x74c67f in ldr_load_pw_file /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:1000
    #7 0x73fecc in john_load /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/john.c:1006
    #8 0x74162b in john_init /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/john.c:1290
    #9 0x7431d2 in main /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/john.c:1730
    #10 0x7f02e6360ec4 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21ec4)

SUMMARY: AddressSanitizer: heap-buffer-overflow ??:0 strcat
Shadow bytes around the buggy address:
  0x0c087fff9b90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c087fff9ba0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c087fff9bb0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c087fff9bc0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c087fff9bd0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c087fff9be0: fa fa 00 00 00 00[02]fa fa fa fd fd fd fd fd fa
  0x0c087fff9bf0: fa fa fd fd fd fd fd fd fa fa fd fd fd fd fd fd
  0x0c087fff9c00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c087fff9c10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c087fff9c20: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c087fff9c30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Contiguous container OOB:fc
  ASan internal:           fe
==26956==ABORTING
Aborted
```

# 2. GDB debug

```C
Program received signal SIGABRT, Aborted.
0x00007ffff5790cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff5790cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff57940d8 in __GI_abort () at abort.c:89
#2  0x00007ffff6f640e9 in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.1
#3  0x00007ffff6f5bde5 in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.1
#4  0x00007ffff6f5fbe2 in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.1
#5  0x00007ffff6f5b279 in __asan_report_error () from /usr/lib/x86_64-linux-gnu/libasan.so.1
#6  0x00007ffff6f321c0 in strcat () from /usr/lib/x86_64-linux-gnu/libasan.so.1
#7  0x0000000000553912 in strcat (__src=0x7ffffffce66a "TAxCfpc1", __dest=0x60400000df10 "$1$JVDBG\302\233\070K$T9H8HK4LZXELP")
    at /usr/include/x86_64-linux-gnu/bits/string3.h:142
#8  prepare (split_fields=0x7ffffffce250, self=0xbb3800 <fmt_NETLMv2>) at NETLMv2_fmt_plug.c:229
#9  0x000000000074745d in ldr_split_line (login=<optimized out>, ciphertext=<optimized out>, gecos=<optimized out>, home=<optimized out>, uid=<optimized out>,
    source=<optimized out>, source@entry=0x0, format=0x12910a8 <database+104>, db_opts=0x6310002821f0, line=0x0) at loader.c:640
#10 0x00000000007483e3 in ldr_load_pw_line (db=db@entry=0x1291040 <database>, line=0x7ffffffce640 "$1$JVDbG\233\070K$T9h8HK4LZxeLP") at loader.c:802
#11 0x0000000000749c97 in read_file (db=db@entry=0x1291040 <database>, name=name@entry=0x631000000868 "out_asan/crashes/id:000020,sig:06,src:000004,op:havoc,rep:16",
    flags=flags@entry=2, process_line=process_line@entry=0x7482a6 <ldr_load_pw_line>) at loader.c:135
#12 0x000000000074c680 in ldr_load_pw_file (db=0x1291040 <database>, name=0x631000000868 "out_asan/crashes/id:000020,sig:06,src:000004,op:havoc,rep:16") at loader.c:1000
#13 0x000000000073fecd in john_load () at john.c:1006
#14 0x000000000074162c in john_init (name=0x7fffffffec07 "john", argc=2, argv=0x7fffffffe968) at john.c:1290
#15 0x00000000007431d3 in main (argc=2, argv=0x7fffffffe968) at john.c:1730
```

**Comment by jfoug** [comment]
I think this is fixed, but I could not get the problem to replicate (bad input file).

@loverszhaokai please retest after 5c0fdf3  and if the problem is gone, close out this issue.

**Comment by loverszhaokai** [comment]
@jfoug  Sorry, there is still a bug. I reduced the hashes and change it to hex.

$ cat pwfile.hex
```
7b736d64357d654c4230515765532445672e5966575938636c5a7543784630784e7238672e
2431244a564462479b384b2454396838484b344c5a78654c503a54696c656b6579636861696e244c623a5441784366706331
```
$ ../base64conv -q -i hex -o raw < pwfile.hex > pwfile
$ cat pwfile
```
{smd5}eLB0QWeS$Eg.YfWY8clZuCxF0xNr8g.
$1$JVDbG�8K$T9h8HK4LZxeLP:Tilekeychain$Lb:TAxCfpc1
```
$ ../john pwfile
```C
arning: detected hash type "md5crypt", but the string is also recognized as "aix-smd5"
Use the "--format=aix-smd5" option to force loading these as that type instead
Warning: invalid UTF-8 seen reading pwfile
=================================================================
==10458==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60400000df32 at pc 0x7f2480c7719b bp 0x7ffc20463eb0 sp 0x7ffc20463670
WRITE of size 9 at 0x60400000df32 thread T0
    #0 0x7f2480c7719a in strcat (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x3019a)
    #1 0x557b8f in strcat /usr/include/x86_64-linux-gnu/bits/string3.h:142
    #2 0x557b8f in prepare /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/NETNTLMv2_fmt_plug.c:238
    #3 0x74e971 in ldr_split_line /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:640
    #4 0x74f8f7 in ldr_load_pw_line /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:802
    #5 0x7511ab in read_file /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:135
    #6 0x753b94 in ldr_load_pw_file /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:1000
    #7 0x747402 in john_load /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/john.c:1006
    #8 0x748b61 in john_init /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/john.c:1290
    #9 0x74a6e7 in main /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/john.c:1728
    #10 0x7f247f4c0ec4 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21ec4)
    #11 0x407032 (/home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/run/john+0x407032)

0x60400000df32 is located 0 bytes to the right of 34-byte region [0x60400000df10,0x60400000df32)
allocated by thread T0 here:
    #0 0x7f2480c9b7df in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x547df)
    #1 0x765241 in mem_alloc_func /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/memory.c:89
    #2 0x557b6d in prepare /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/NETNTLMv2_fmt_plug.c:233
    #3 0x74e971 in ldr_split_line /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:640
    #4 0x74f8f7 in ldr_load_pw_line /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:802
    #5 0x7511ab in read_file /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:135
    #6 0x753b94 in ldr_load_pw_file /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:1000
    #7 0x747402 in john_load /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/john.c:1006
    #8 0x748b61 in john_init /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/john.c:1290
    #9 0x74a6e7 in main /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/john.c:1728
    #10 0x7f247f4c0ec4 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21ec4)

SUMMARY: AddressSanitizer: heap-buffer-overflow ??:0 strcat
Shadow bytes around the buggy address:
  0x0c087fff9b90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c087fff9ba0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c087fff9bb0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c087fff9bc0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c087fff9bd0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c087fff9be0: fa fa 00 00 00 00[02]fa fa fa fd fd fd fd fd fd
  0x0c087fff9bf0: fa fa fd fd fd fd fd fa fa fa fd fd fd fd fd fd
  0x0c087fff9c00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c087fff9c10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c087fff9c20: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c087fff9c30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Contiguous container OOB:fc
  ASan internal:           fe
==10458==ABORTING
Aborted (core dumped)
```

**Comment by magnumripper** [comment]
> @jfoug Sorry, there is still a bug

According to your report it now crashes in md5crypt, so that is a new issue, and this one is fixed.

**Comment by jfoug** [comment]
No, the crash went from 
``` #2 0x553911 in prepare /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/NETLMv2_fmt_plug.c:229```

to
```
#2 0x557b8f in prepare /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/NETNTLMv2_fmt_plug.c:238
```

So the original bug was not showing, but it was not showing up in the prepare() for NET-NTLMv2

We talked about that code also needing fixed. I did not fix it until I heard the first patch had fixed the problem there. Again, I 'thought' that was the problem, but I had not way to test.

**Comment by magnumripper** [comment]
My bad, I see now: It did pick md5crypt but it still tests all other formats just for the *Warning: detected hash type foo, but the string is also recognized as bar* and while doing that it crashed in NTLMv2...

**Comment by magnumripper** [comment]
But anyway it's a new format and thus a new issue!
