### ISSUE TITLE
Raw-MD5-opencl fails self test

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1509]
```
Device 0: AMD Opteron(TM) Processor 6272                 

Testing: Raw-MD5-opencl [MD5 OpenCL]... Error, crypt_all kernel.
```

https://travis-ci.org/magnumripper/JohnTheRipper/jobs/69812898

**Comment by magnumripper** [comment]
af6a034

OSX
```
$ for i in 0 1 2; do ../run/john -test=0 -form:raw-md5-opencl -dev=$i; done
Device 0: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
Testing: Raw-MD5-opencl [MD5 OpenCL]... PASS
Device 1: HD Graphics 4000
Testing: Raw-MD5-opencl [MD5 OpenCL]... PASS
Device 2: GeForce GT 650M
Testing: Raw-MD5-opencl [MD5 OpenCL]... PASS
```

Super
```
$ for i in 1 2 3 4 5 ; do ../run/john -test=0 -dev=$i -form:raw-md5-opencl -verb=2 ; done
Device 1: Tahiti [AMD Radeon HD 7900 Series]
Testing: Raw-MD5-opencl [MD5 OpenCL]... Error, crypt_all kernel.
Device 2: Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
Testing: Raw-MD5-opencl [MD5 OpenCL]... Error, crypt_all kernel.
Device 3: Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
Testing: Raw-MD5-opencl [MD5 OpenCL]... Segmentation fault
Device 4: Intel(R) Many Integrated Core Acceleration Card
Testing: Raw-MD5-opencl [MD5 OpenCL]... PASS
Device 5: GeForce GTX TITAN
Testing: Raw-MD5-opencl [MD5 OpenCL]... OpenCL error (CL_OUT_OF_RESOURCES) in file (opencl_rawmd5_fmt_plug.c) at line (779) - (failed in reading back num cracked hashes.)
```

**Comment by magnumripper** [comment]
Fixed in 9b4759a

**Comment by magnumripper** [comment]
Still fails on Travis

**Comment by frank-dittrich** [comment]
On Travis, Raw-MD5-opencl self test still fails for gcc and clang builds.

**Comment by jfoug** [comment]
Fixed on Travis
