### ISSUE TITLE
Generate and host updated builds for macOS

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2674]
See https://github.com/magnumripper/JohnTheRipper/issues/869 for the details.

I think https://docs.travis-ci.com/user/uploading-artifacts/ can help in completing this task.

**Comment by kholia** [comment]
@magnumripper I think this will need work from your side. 

Here are two references,

https://docs.travis-ci.com/user/deployment/releases/

https://github.com/kholia/JohnTheRipper/tree/macOS (top commit)

It seems that I am unable to publish builds ("releases") for `magnumripper/JohnTheRipper/` slug.

**Comment by kholia** [comment]
I think I have all the pieces required now. https://github.com/kholia/JohnTheRipper/releases now has a macOS build available :-)

Remember to use `travis encrypt "GitHub token" -r <username>/JohnTheRipper` command to generate the secure API key. The GitHub token needs to be generated from the https://github.com/settings/tokens page with a `repo` scope.

**Comment by solardiz** [comment]
> https://github.com/kholia/JohnTheRipper/releases now has a macOS build available :-)

Cool. But I guess it's for specific CPU features? I think we need at least SSE2-only and AVX2-enabled builds. BTW, the same applies to our automated Windows builds.

**Comment by kholia** [comment]
I am not sure about the CPU features being used by the current macOS build. I will check this out.

I will look into how I can do SSE2-only and AVX2 builds. Tips around this topic are highly welcome!

**Comment by solardiz** [comment]
> I will look into how I can do SSE2-only and AVX2 builds.

I think "./configure --disable-native-tests" should result in an SSE2-only build. As to an AVX2 build, it should happen by default if the underlying system has AVX2. If not, then you might be able to force that, but it gets trickier - you'll have to override the CFLAGS, yet not drop (so re-introduce) the original contents of CFLAGS (or else other optimizations will be lost). Hopefully, the build system would just happen to be AVX2-capable.

**Comment by magnumripper** [comment]
$ ./configure --help
```
  --disable-native-tests  Do not test build system for target features.
                          Implies --disable-native-march.
  --disable-native-march  Do not use things like -march=native even if valid
                          compiler option(s). Native tests still can be run in
                          this mode
```

**Comment by magnumripper** [comment]
I believe `./configure CPPFLAGS=-mavx2 --disable-native-tests` should produce an AVX2 build on many non-AVX2 build hosts. It doesn't work on my Macbook though, for some reason it ends up producing an SSE2 build.

**Comment by solardiz** [comment]
What the point behind `--disable-native-march`? What are those native tests we'd want to run if we don't(?) produce a native build?

BTW, this reminds me: in my recent testing of php_mt_seed, I found that `-march=native` caused an 8% slowdown on Haswell compared to `-mavx2`. I worked around that by adding `-mtune=generic` right after `-march=native`. This is a gcc issue (I think its attempt at better instruction scheduling for Haswell fails when the source code contains more than a usual amount of parallelism, such as through explicit interleaving, like we do in both of these projects), but anyhow we might want to see if adding `-mtune=generic` provides a net speedup for JtR as well.

**Comment by solardiz** [comment]
> ./configure CPPFLAGS=-mavx2 --disable-native-tests

Doesn't that leave CFLAGS without `-mavx2`?

**Comment by magnumripper** [comment]
> What the point behind `--disable-native-march`?

Many systems doesn't (or didn't) have `-march=native`. At first it was a Linux-only option.

>> ./configure CPPFLAGS=-mavx2 --disable-native-tests
>
> Doesn't that leave CFLAGS without `-mavx2`?

Apparently it does (I believe the above worked long ago). This works fine right now on my AVX Macbook:
```
./configure CFLAGS="-mavx2 -O2 -g" --disable-native-tests
```

**Comment by magnumripper** [comment]
> At first it was a Linux-only option.

In fact it's still listed as such in the gcc-7 manpage although it has worked fine on OSX for years.

```
-march=native causes the compiler to auto-detect the architecture of the build
computer.  At present, this feature is only supported on GNU/Linux, and not all
architectures are recognized.  If the auto-detect is unsuccessful the option has
no effect.
```

**Comment by solardiz** [comment]
> ./configure CFLAGS="-mavx2 -O2 -g" --disable-native-tests

Doesn't this miss other optimization options that we normally use? Perhaps `-fomit-frame-pointer`?

**Comment by magnumripper** [comment]
The other options are added afterwards. On my system, CFLAGS defaults to "-O2 -g". I can't remember if that's a property of gcc or of autoconf.

**Comment by magnumripper** [comment]
The compilation of simd-intrinsics.c ends up like this with my mentioned CFLAGS:
```
gcc -DAC_BUILT -mavx2 -DJOHN_AVX2 -c -mavx2 -O2 -g -I/usr/local/include -DARCH_LITTLE_ENDIAN=1   -Wall -Wdeclaration-after-statement -fomit-frame-pointer --param allow-store-data-races=0 -Wno-deprecated-declarations  -Wunused-but-set-variable -std=gnu89 -Wdate-time   -fopenmp  -D_THREAD_SAFE -pthread   -I/usr/local/opt/openssl/include -I/usr/local/include -DHAVE_OPENCL -D_THREAD_SAFE -pthread -funroll-loops simd-intrinsics.c -o simd-intrinsics.o
```
Not sure what caused the double `-mavx2` but it doesn't cause any troube.

**Comment by kholia** [comment]
I could not do a SSE2-only build so far. The current build configurations commands can be seen at,
https://github.com/kholia/JohnTheRipper/blob/macOS/.travis/check.sh

Here is a SSE4.1 + AVX2 combo build,
https://github.com/kholia/JohnTheRipper/releases/download/macOS-3/JtR-macOS.zip

@magnumripper Can you please check if the `john-avx2` binary from this build is working on your AVX2 Mac system? My Mac VM does not support AVX2.

This builds require OpenSSL + GMP to be installed (brew install --force openssl gmp).

**Comment by magnumripper** [comment]
> I could not do a SSE2-only build so far

Try adding `CFLAGS=-mno-sse4.1 -O2 -g` to that one.

> @magnumripper Can you please check if the john-avx2 binary from this build

I currently only have an AVX Macbook so I can't test AVX2.

**Comment by magnumripper** [comment]
Well I could test it anyway of course.
```
$ run/john-avx2 
Illegal instruction: 4
```
That's strange. It should say "Sorry, this build requires AVX2" or something like that.

**Comment by magnumripper** [comment]
```
Process 6939 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x00000001002756bf john-avx2`CRC32_Init_tab + 31
john-avx2`CRC32_Init_tab:
->  0x1002756bf <+31>: vpbroadcastd 0x1acb78(%rip), %ymm0     ; padding + 160
    0x1002756c8 <+40>: vpxor  %ymm3, %ymm3, %ymm3
    0x1002756cc <+44>: vpbroadcastd 0x1bf66b(%rip), %ymm4     ; itoa16u + 144
    0x1002756d5 <+53>: leaq   0x4ce644(%rip), %rcx      ; JTR_CRC32_table
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
  * frame #0: 0x00000001002756bf john-avx2`CRC32_Init_tab + 31
    frame #1: 0x000000010027d137 john-avx2`main + 135
    frame #2: 0x00007fffad736235 libdyld.dylib`start + 1
    frame #3: 0x00007fffad736235 libdyld.dylib`start + 1
```

**Comment by magnumripper** [comment]
>>> ./configure CPPFLAGS=-mavx2 --disable-native-tests
>>
>> Doesn't that leave CFLAGS without `-mavx2`?
>
> Apparently it does (I believe the above worked long ago).

CPPFLAGS is added everywhere needed, so using `CPPFLAGS=-mavx2` is actually safer. The problem I had yesterday was that I later overwrote CPPFLAGS with an `-I/usr/local/include(...)`.

@kholia try dropping `CFLAGS` from your line and using `CPPFLAGS=-mavx2` instead. I believe that will end up better (for reasons we might want to dig into).

**Comment by magnumripper** [comment]
I had a look at Makefile. Using CPPFLAGS should be no different from CFLAGS, as we end up with a final CFLAGS that end with CPPFLAGS. I think my faiblesse for using CPPFLAGS (which is not very logical) comes from the fact I don't have to add the `-O2 -g`...

**Comment by magnumripper** [comment]
BTW see also https://github.com/magnumripper/JohnTheRipper/wiki/Fallback-binary-chains

**Comment by kholia** [comment]
This page is super useful.

Will using `CFLAGS=-mavx ...` (not mavx2) generate builds which we can test on your Mac system?

I will create a VM to test this "fallback binary chains" stuff. It seems too wonderful to me. Does it really work? :-)

**Comment by magnumripper** [comment]
> Will using CFLAGS=-mavx ... (not mavx2) generate builds which we can test on your Mac system?

It should. I just tested building here using your AVX2 configure line, and I do get the "Sorry, AVX2 is required for this build". I wonder why I got "Illegal instruction: 4" using your binary.

> I will create a VM to test this "fallback binary chains" stuff. It seems too wonderful to me. Does it really work? :-)

Sure, it's tested on Linux and OSX.

**Comment by magnumripper** [comment]
@kholia if you try out CPU fallback, be sure to have 648b13fe first!

**Comment by kholia** [comment]
> I do get the "Sorry, AVX2 is required for this build". I wonder why I got "Illegal instruction: 4" using your binary.

This difference is very weird and I can't think of a reason.

I will give CPU fallback (with that commit) a try tomorrow. It is time for bed here.

**Comment by magnumripper** [comment]
> This difference is very weird and I can't think of a reason.

That's what was fixed in #2679 - it's history now! Some compiler optimization decided to use AVX2 instructions for `CRC32_Init_tab()` and Jim had placed that function prior to the CPU detection/fallback. The problem has been there since June 2015 but I never saw it surfacing until now.

**Comment by kholia** [comment]
CPU detection is working great now. Fallback binary chain stuff also seems to be working fine. 👍 for both.

I am still having problems generating SSE2-only builds. I see the following errors in Travis CI,

```
checking for MMX... no
checking for arch.h alternative... x86-64.h
checking for 32/64 bit... 32-bit
checking for extra ASFLAGS... clang: error: unsupported argument '-q' to option 'Wa,'
None needed
checking for X32 ABI... no
checking for byte ordering according to target triple... little
checking supplied paths for OpenSSL...  
checking additional paths for OpenSSL... none
checking openssl/opensslv.h usability... no
checking openssl/opensslv.h presence... yes
configure: WARNING: openssl/opensslv.h: present but cannot be compiled
configure: WARNING: openssl/opensslv.h:     check for missing prerequisite headers?
configure: WARNING: openssl/opensslv.h: see the Autoconf documentation
configure: WARNING: openssl/opensslv.h:     section "Present But Cannot Be Compiled"
configure: WARNING: openssl/opensslv.h: proceeding with the compiler's result
configure: WARNING:     ## ------------------------------------------------------ ##
configure: WARNING:     ## Report this to john-users mailing list at openwall.com ##
configure: WARNING:     ## ------------------------------------------------------ ##
checking for openssl/opensslv.h... no
configure: error: JtR requires OpenSSL headers being installed
See `config.log' for more details
```

I am using the following configure command,

`./configure --disable-native-tests CPPFLAGS="-mno-ssse3 -I/usr/local/opt/openssl/include" LDFLAGS="-L/usr/local/opt/openssl/lib`

**Comment by solardiz** [comment]
> For now I will generate SSE4.1 and AVX2 binaries. macOS Sierra requires SSE4.1 to run.

That's what I thought: if SSE4.1 gets enabled by default even without `-march=native`, maybe that's because the versions of OS X the binary would be able to run on require SSE4.1 anyway. If so, it's pointless to build an SSE2-only binary for those versions of OS X. An SSE2-only binary would make sense only if it's also runnable on OS X old enough that it could potentially run on hardware lacking SSE4.1.

And there's no point in going below SSSE3 in any OS X build, because Core 2 Duo already supported SSSE3 and that's what was found in the earliest widespread Intel Macs and (I think) what the earliest x86-64 releases of OS X would run on (we're talking 64-bit builds of JtR anyway).

So my comment about needing an SSE2-only build was wrong. The oldest we might want to support is SSSE3 or SSE4.1, depending on target OS X versions.

**Comment by kholia** [comment]
Latest AVX2 enabled macOS builds with automatic fallback to SSE4.1 are now available at https://github.com/kholia/JohnTheRipper/releases.

Please test them.

These builds have only been tested on macOS Sierra and not on older OS X. Generating and testing builds for older OS X would require more work.

**Comment by magnumripper** [comment]
They seem to work (having only AVX, I ran "john" but it ended up running "john-sse4.1") but you should add an AVX version inbetween. So AVX2 -> AVX -> SSE4.1. The performance drop from AVX to SSE4.1 is significant:
```
Benchmarking: NT [MD4 128/128 SSE4.1 4x4]... DONE
Raw:	37543K c/s real, 37543K c/s virtual

Benchmarking: NT [MD4 128/128 AVX 4x3]... DONE
Raw:	48555K c/s real, 48075K c/s virtual
```

**Comment by kholia** [comment]
I will add the AVX binary right away. Thanks for testing this stuff 👍

**Comment by magnumripper** [comment]
> The performance drop from AVX to SSE4.1 is significant

On the other hand this may be compiler differences as well. I see your build was made with clang 8.1.0, my build (the AVX version above) used gcc 7.1.0

**Comment by kholia** [comment]
The only problem with generating multiple builds is the increase in the CI testing time required. I don't have the numbers right now but let's hope that the situation is bearable.

**Comment by kholia** [comment]
@magnumripper macOS build with AVX2->AVX->SSE4.1 fallback is ready for testing at the following URL,

https://github.com/kholia/JohnTheRipper/releases.

Use the build associated with `macOS-7` tag.

**Comment by kholia** [comment]
Great! 

I can help in setting this up for the official repository. 

One catch is that the publication of a build requires a `tag` to be associated to the corresponding commit. E.g. Commit  5bc79e5 has tag `macOS-7` associated with it in my repository.

**Comment by solardiz** [comment]
> The difference between a clang build and gcc is huge, but that's another story.

Note also that you had 4x3 with gcc and Dhiru gets 4x4 with clang. Maybe we need to re-tune this for current clang. Maybe 4x3 will be optimal for it as well, just like it is(?) for gcc.

**Comment by magnumripper** [comment]
> One catch is that the publication of a build requires a tag to be associated to the corresponding commit. E.g. Commit 5bc79e5 has tag macOS-7 associated with it in my repository.

Perhaps "macOS-20170818" is better? "macOS-7" sound like an OS version.

Just for the record I am and always was a bit weary about binary releases, especially automated ones. I don't want to be "associated" with them in any way. Someone could take "release" as some kind of quality measure, for a starter.

**Comment by kholia** [comment]
Yes, `macOS-20170818` is a lot better than `macOS-7`. I will start using this naming scheme.

I understand your concerns about binary builds. It would not be great if we start getting newbie level support questions around binary builds on GitHub.

**Comment by solardiz** [comment]
> Someone could take "release" as some kind of quality measure

We should call these things "snapshots" or "builds" for that reason.

> Yes, macOS-20170818 is a lot better than macOS-7. I will start using this naming scheme.

How about `macosx-20170818`, consistent with our (legacy) make target names.

**Comment by kholia** [comment]
These builds are for macOS (the new OS name) and not for OS X. So using the `macOS` base word seems more appropriate to me. Something like `macOS-20170818-snapshot` should work I think.

**Comment by magnumripper** [comment]
"snapshot" is good. I guess it will still be listed under "releases" on GitHub, but with "snapshot" in the name we're kinda home free.

**Comment by kholia** [comment]
One problem which I just noticed is that the build distribution size is not optimal.

All the binaries (e.g. zip2john, racf2john) which use the symlink-to-john trick aren't handled well by the zip command, which leads to increased size of the compressed build archive.

```
$ du -hs racf2john bitlocker2john 
6.5M	racf2john
16K	bitlocker2john
```

Notice the large size difference in the above output.

I tried using tar + xz compression but it is too slow. The output archive is also hard to use on macOS. The tar + bz2 compression doesn't compress well.

I am experimenting with removing the symlink-to-john trick for some binaries to see the impact on the final compressed archive size.

**Comment by solardiz** [comment]
> All the binaries (e.g. zip2john, racf2john) which use the symlink-to-john trick aren't handled well by the zip command

Maybe you need this option to `zip`:

```
       -y     Store  symbolic  links  as  such  in the zip archive, instead of compressing and storing the file
              referred to by the link (UNIX only).
```

**Comment by kholia** [comment]
Thank you! By using this `-y` zip option the output size went from 60.6 MB to 36.5 MB.

I am wondering if there is still room for more reduction in the output size.

**Comment by kholia** [comment]
Using 7-Zip further reduces the output archive size to 15 MB, and that too in a reasonable amount of time!

We already require macOS users to run `brew install openssl gmp`. Maybe they can be requested to run `brew install p7zip` as well to extract such output `7z` archives?

**Comment by solardiz** [comment]
> Maybe they can be requested to run brew install p7zip as well to extract such output 7z archives?

I guess so, but doesn't `xz` compress just as well? Is `xz` available on macOS by default?

**Comment by kholia** [comment]
I believe that macOS has `xz` available by default. I will double check. The `tar + xz` combination takes more time, and doesn't compress as well as 7-Zip.

```
$ time 7z a JtR.7z X  # X has the contents of the build
7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
...
Archive size: 15511664 bytes (15 MiB)
Everything is Ok

real	0m19.625s
user	0m28.826s
sys	0m0.322s

$ time tar -cJf JtR.tar.xz X

real	0m30.973s
user	0m30.709s
sys	0m0.233s

$ du -hs JtR.tar.xz 
27M	JtR.tar.xz
```

**Comment by solardiz** [comment]
> The tar + xz combination takes more time, and doesn't compress as well as 7-Zip.

I think you can fix that (and maybe even improve upon 7-Zip's result) by sorting the file list such that similar files are closer together in tar's output stream. For example, here's what I used to repackage Nmap source tarball for Owl:

    tar cJf %SOURCE0 --owner=root --group=root `find %srcname ! -type d | sort -i -t / -k 3 | sort -i -t . -k 3`

The `-k 3` would probably be wrong and need to be adjusted.

I think 7-Zip performs something similar internally.

**Comment by kholia** [comment]
Using this trick (with `-k 3` / `-k 4`) reduced the archive size from 27M to 23M. 7-Zip still leads with a size of 15M.

**Comment by magnumripper** [comment]
Maybe you want to `make strip` as well (if you don't already) before archiving, that should do quite some difference.

**Comment by magnumripper** [comment]
BTW you obviously don't have to strip in a separate step - just change eg. `make -sj4` to `make -sj4 strip`.

**Comment by kholia** [comment]
I think that using `strip` on the binaries would break generation of nice backtraces (from gdb / lldb) in case of crashes.

**Comment by magnumripper** [comment]
Sure but most people needing a precompiled binary don't know squat about how to use a debugger anyway. I'm curious how much smaller it'd make the archive. Perhaps not that much?

**Comment by kholia** [comment]
Hmm, fair point. I am giving `strip` a try right now.

**Comment by kholia** [comment]
Enabling `strip` reduced the output archive size from 14.8M to 14.4M. I was expecting way more.

As usual, https://github.com/kholia/JohnTheRipper/releases has the builds.

**Comment by magnumripper** [comment]
Wow, I guess debug info packs real well. In that case I agree it's better not stripping.

**Comment by kholia** [comment]
I got AVX and AVX2 working on my virtual Mac.

```
$ sysctl -a | grep leaf7
machdep.cpu.leaf7_features: SMEP BMI1 AVX2 BMI2
machdep.cpu.leaf7_feature_bits: 424

$ ../run/john --test --format=descrypt
Benchmarking: descrypt, traditional crypt(3) [DES 128/128 AVX-16]... DONE
Many salts:	5077K c/s real, 5077K c/s virtual
Only one salt:	4893K c/s real, 4893K c/s virtual

$ CPUID_DISABLE=1 ../run/john --test --format=descrypt  # disable CPU features detection
Benchmarking: descrypt, traditional crypt(3) [DES 256/256 AVX2-16]... DONE
Many salts:	9424K c/s real, 9424K c/s virtual
Only one salt:	8893K c/s real, 8893K c/s virtual
```

However, I have to disable the `CPU_detect` function to make use of `AVX2` extensions.

It seems that we may need to tweak our `CPU_detect` function a bit for macOS. Or maybe I need to expose `MOVBE + FMA3` CPU extensions to the macOS guest?

**Comment by kholia** [comment]
From x86-64.S,

```
#define CF_AVX                  $0x1C000000 /* AVX + XSAVE + OSXSAVE */
#define CF_AVX2                 $0x1C401000 /* the above + MOVBE + FMA3 */
```

From commit f9338ccaeec94949a2e7f4a7cb54da9a1919750d,  "The AVX2 check is very quick and dirty, not using leaf 7 nor extended flags but it should be sufficient for a starter".

Somehow the AVX2 detection is failing on my virtual Mac. It seems that neither my host CPU (i7-6600U) nor the guest CPU supports the `FMA3` extension.  On host, AVX2 detection works fine but on the guest VM I have to use the `CPUID_DISABLE=1` hack to use AVX2.

@magnumripper Do you have any tips on this topic? Thanks!

**Comment by kholia** [comment]
https://github.com/tycho/cpuid generated dumps from host and guest,

* [cpuid-host.txt](https://github.com/magnumripper/JohnTheRipper/files/1271962/cpuid-host.txt)
* [cpuid-host-raw.txt](https://github.com/magnumripper/JohnTheRipper/files/1271963/cpuid-host-raw.txt)
* [cpuid-macOS.txt](https://github.com/magnumripper/JohnTheRipper/files/1271964/cpuid-macOS.txt)
* [cpuid-macOS-raw.txt](https://github.com/magnumripper/JohnTheRipper/files/1271965/cpuid-macOS-raw.txt)

**Comment by magnumripper** [comment]
> Somehow the AVX2 detection is failing on my virtual Mac

We've seen problems with virtual machines before and AFAIK it's a problem with them, not with JtR. Having said that, I'd welcome a patch that works around the problems without introducing other problems.

**Comment by magnumripper** [comment]
#1986 #2089 #2384

**Comment by kholia** [comment]
Thanks for the references 👍 

It is a minor problem (an inconvenience rather) which I can workaround by `CPUID_DISABLE=1` hack. I will stop worrying about it now :-)

**Comment by solardiz** [comment]
> We've seen problems with virtual machines before and AFAIK it's a problem with them, not with JtR.

In general yes, but in this case per Dhiru's comments above we actually know our check for AVX2 is wrong - it doesn't check for AVX2, but rather checks for MOVBE and FMA3, neither of which we use. We should have a separate issue for fixing this (implement proper AVX2 detection).

**Comment by magnumripper** [comment]
>  it doesn't check for AVX2, but rather checks for MOVBE and FMA3, neither of which we use

True. I've had that in mind for a while, I'll create a proper issue for it.

**Comment by magnumripper** [comment]
Like I said in #2716, everything is exactly as it should be (at least for 64-bit). 

> It seems that neither my host CPU (i7-6600U) nor the guest CPU supports the FMA3 extension

That CPU does have FMA3.
