### ISSUE TITLE
ethereum and phpass both have salt alignment issues

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#2956]
On 32 bit builds, both of these format have salt alignment issues listed.  Likely using ARCH_WORD or something somewhere, where it should be some other size alignment.

**Comment by kholia** [comment]
How do I reproduce this locally?

**Comment by jfoug** [comment]
build on 32 bit.

**Comment by jfoug** [comment]
This change on phpass:  NOTE, not sure why 8 byte using PHPASS_SALT_ALIGN, but i am ignoring that for now ;)    I am sure that ethereum is same type problem.

```diff
static void * salt(char *ciphertext)
{
	static union {
		unsigned char salt[SALT_SIZE+2];
-		uint32_t x;
+		uint64_t x; // PHPASS_SALT_ALIGN set to 8
	} x;
	unsigned char *salt = x.salt;
```

**Comment by solardiz** [comment]
Perhaps we should reduce PHPASS_SALT_ALIGN to 4 instead.

**Comment by jfoug** [comment]
The PHPASS_SALT_ALIGN is in common code, so is used in multiple builds.  Yes, it may be possible to reduce the size.  IT does depend upon just HOW the salt is used, and what the max required usage alignment is.  If there are ARCH_WORDS in it, then it must be set to that value. If there is some version of build that indexes it as a uint64 (since the 'real' salt is 8 bytes), then it needs to be set to 8 bytes.  It may have been set to 8, to get a cracks to stop.  NOW that we have UBSan align code as a build target, we actually can determine  if an alignment is too small, easily.  It IS safe to set to 8, and always make sure we align the return of salt() to 8, and that would satisfy all builds. Yes, it may waste 4 bytes IF the build can get by with just 4 byte alignment
Actually, there may be some builds which require no alignment.  This is the case for MANY formats. But even there, if ANY format requires a 4 byte alignment, then the format is set to ALWAYS align to 4.  Now on phpass, if there is ANY build that requires 8, then by convention, we would set alignment to 8, and then make sure that all builds honor that.

**Comment by magnumripper** [comment]
> How do I reproduce this locally?

You don't need to. Look at the code, fix the mismatch.

**Comment by jfoug** [comment]
When there were mismatches, unless I know better, I always target to the highest usage (well, when it was ARCH_WORD, I investigate and see).  phpass is 8 'bytes' of salt.  But if there is somewhere loading it all 8 bytes at one time (say in SIMD land, or opencl land), then it should be set to 8 bytes GLOBALLY, in the salt_align field, and within whatever union / alloc_aligned code creates it. 

If it is allocating, the the easiest way, is to allocate aligned, AND use the alignment of SALT_ALIGN   That way, if alignment does change somewhere else, a rebuild gets things back in sync.

**Comment by magnumripper** [comment]
#2965 should fix this

**Comment by jfoug** [comment]
validated on 32 bit that this warning is gone.  Closing.

**Comment by magnumripper** [comment]
CircleCI, 32 bit NON-SIMD Linux
```
Testing: phpass ($P$9) [phpass ($P$ or $H$) 32/32]... Warning: salt() returned misaligned pointer
PASS
```

**Comment by magnumripper** [comment]
I must say I can't see why it fails now. SALT_ALIGN is 8 and get_salt() does satisfy that.

**Comment by jfoug** [comment]
0d9539f  should fix the problem.  Once I see this warning gone from the build bot, I will close this bug.

**Comment by magnumripper** [comment]
PHPass still failing.
https://circleci.com/gh/jfoug/JohnTheRipper/59?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by magnumripper** [comment]
No wait, that PR might be built on older version

**Comment by jfoug** [comment]
I was wondering wtf was going on.  I looked at the circleci report from the check mark on the 
0d9539f build, and could NOT find a salt align problem.  So these messages caught me off guard.  glad you guys figured it out, and re-closed this issue.

Btw, I have NO reason why aligning to 8 bytes was failing.  I really do not.  unless the single variable uint64_t (which the compiler could see was unused) was not enough to properly trigger it to align.  Other than that (call it an optimization bug), I have no idea why the 8 byte alignment failed.

BUT there is no reason to align 8 bytes.  The worst alignment usage of salt only need alignment for uint32_t, so i made it that way.
